### ISSUE TITLE
Setting ownership qos

### ISSUE THREAD

**Issue by VectorUrsRudolph** [rticommunity/rticonnextdds-connector#65]
Hi,
I try to connect to my topic with exclusive ownership, but the connector shows alway up with shared ownership.

The xml section is:
`  <qos_library name="QosLibrary"> 
		<qos_profile name="DefaultProfile" is_default_qos="true" base_name="BuiltinQosLibExp::Generic.StrictReliable">
      <topic_qos>
        <durability>
          <kind>VOLATILE_DURABILITY_QOS</kind>
        </durability>
        <reliability>
          <kind>RELIABLE_RELIABILITY_QOS</kind>
          <max_blocking_time>
            <sec>10</sec>
            <nanosec>0</nanosec>
          </max_blocking_time>
        </reliability>
        <ownership>
          <kind>EXCLUSIVE_OWNERSHIP_QOS</kind>
        </ownership>
      </topic_qos>
		</qos_profile>`

Any ideas?

**Comment by samuelraeburn** [comment]
Hi,

I believe the issue is that you are using topic_qos tags to configure your QoS. Internally Connector is based on top of XML Application Creation which doesn't expose any way of doing this out of the box. It might be possible to achieve what you are trying to do with <topic_qos>, but the easiest option would be for you to place your QoS in <datareader_qos> and <datawriter_qos> tags:

```
<datawriter_qos>
    <durability>
        <kind>VOLATILE_DURABILITY</kind>
    </durability>
    <reliability>
        <kind>RELIABLE_RELIABILITY_QOS</kind>
        <max_blocking_time>
            <sec>10</sec>
            <nanosec>0</nanosec>
        </max_blocking_time>
    </reliability>
    <ownership>
        <kind>EXCLUSIVE_OWNERSHIP_QOS</kind>
    </ownership>
</datawriter_qos>
<datareader_qos>
    <durability>
        <kind>VOLATILE_DURABILITY</kind>
    </durability>
    <reliability>
        <kind>RELIABLE_RELIABILITY_QOS</kind>
        <max_blocking_time>
            <sec>10</sec>
            <nanosec>0</nanosec>
        </max_blocking_time>
    </reliability>
    <ownership>
        <kind>EXCLUSIVE_OWNERSHIP_QOS</kind>
    </ownership>
</datareader_qos>
```
I tested this using the shipped Connector example and the ownership QoS policy was correctly applied.

Is this a possibility for your use-case?
Sam

**Comment by VectorUrsRudolph** [comment]
This works for me, thanks! 
I think I tried this before but for somehow reasons it don't worked.
