### ISSUE TITLE
Problem with unbounded sequence

### ISSUE THREAD

**Issue by VectorUrsRudolph** [rticommunity/rticonnextdds-connector#66]
Hi,
I am struggling to get a C++-Application(with idl) and a javascript application (with xml ) connected.
In my idl file I have an unbounded sequence and in my  xml I have set the member property sequenceMaxLength="-1". 
In my Admin-Console I get a Data type mismatch. The idl-application sets the sequence size to 2147483647 (looks like max signed int), in the xml-application the sequence size is set to 100. All other members and properties are the same, except the sequence length.
Do you have some hints to get the members matching?

**Comment by samuelraeburn** [comment]
Hi,

I think the issue is that you are using a Connector based on top of a pre-6.0.0 Connext DDS Core.
As mentioned in the Connect migration guide (https://community.rti.com/static/documentation/connext-dds/6.0.0/doc/manuals/migration_guide/general.html?#unbounded-sequences-and-strings-in-xml-type-representation) the behaviour of unbounded sequences was changed between pre- and post-6.0.0 releases of Connext DDS.
If possible, please could you try upgrading your version of Connector to the newest version? I would expect this to fix any matching issues you are having between your applications.

When you upgrade to a newer version of Connector, you should be aware that in newer releases arrays are 0-indexed (whereas previously they were 1-indexed) - something to take into account when migrating.

Hope that's useful,
Sam

**Comment by VectorUrsRudolph** [comment]
Hi,
took me some time, but the problem is fixed with the newest version.
Thanks for your help!
